### ISSUE TITLE
BEPU Physics demo!

### ISSUE THREAD

**Issue by LukeTOBrien** [WaveEngine/WebGL.NET#10]
Hi there,

I am interested in your project and what you have done seems really great with a lot of potentual.  
Some suggestions I have  about your [demo site](https://webgldotnet.surge.sh/):

* I think it would be a good idea to add some navigation to the demo site, this could be done using [Blazor ](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor) for eg.  
  Each demo should be displayed on it's own, to keep focus on the demo we are looking at.
* If you could do some [BEPU Physics demos](https://www.bepuentertainment.com/) that would be truely awesome!

Just some ideas.  
What do you think? :-)

**Comment by MarcosCobena** [comment]
Hi @LukeTOBrien,

Thanks for your comments:
- I think we considered such navigation at the initial phase but we ended up with everything together because the whole page goes through the same update & draw cycle, and that helped us test the performance at some point;
- Yeah, that'd be cool, but I feel it'd be out of scope here, since we're focusing on pure WebGL. However, a physics demo is something we may be working on with Wave Engine, since we support such feature but still have not made anything in Wasm

Again, thanks!

—Marcos

**Comment by LukeTOBrien** [comment]
Thanks.

Is Wave Engine a free for commercial use?

I am using ThreeJS for a project that isn't even commercial yet, but in
(perhaps very) long turn I would want to use Wasm, so I am very interested
in your progress!

**Comment by MarcosCobena** [comment]
Yep! :-)

![imagen](https://user-images.githubusercontent.com/1142782/74216522-037c1600-4ca5-11ea-855d-8728fc1915ae.png)

https://waveengine.net/

Let me please close this issue, but feel free to reopen it if needed.
