### ISSUE TITLE
BufferData does not accept ArrayBuffer or ArrayBufferView under WebGL 1

### ISSUE THREAD

**Issue by harry-cpp** [WaveEngine/WebGL.NET#12]
BufferData does not accept ArrayBuffer or ArrayBufferView with WebGL 1, only 2 overrides are size and System.Array.

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferData

**Comment by MarcosCobena** [comment]
Hi!

You are correct, we commented the mentioned typedef, surely because didn't know how to transpile such by that time:

https://github.com/WaveEngine/WebGL.NET/blob/ab82649a1d2d54f79249b2ba0f71b7cfe1c283f1/src/WebIDLToCSharp/webgl.idl#L522

It should be easy to recover it back, let me try to book some time for this.

Thanks!

—Marcos

**Comment by MarcosCobena** [comment]
Hi again @harry-cpp,

I've added a test which uses a System.Array to provide data to the call, which is the way we'd expect to work from .NET (although can be improved with Span<T>, for instance):

https://github.com/WaveEngine/WebGL.NET/blob/6545c4284cdaf6e2bb1699d40a09c56086c70a2c/src/Tests/WebGL1Tests.cs#L56

In order to help you better, could you paste here some code on what you'd like to achieve?

Thanks!

**Comment by harry-cpp** [comment]
Here is an example method of WebGL 2 code that will not work under WebGL 1:
https://github.com/harry-cpp/MonoGame/blob/wasm/MonoGame.Framework/Platform/Graphics/GraphicsDevice.Web.cs#L775

**Comment by MarcosCobena** [comment]
OK! I got it; let me work on this :-) Thanks!

**Comment by MarcosCobena** [comment]
There we go! Give it some mins:

https://www.nuget.org/packages/WebGLDotNET/2.1.0

Thanks and cheer up with MonoGame! :-)

**Comment by MarcosCobena** [comment]
Sorry, just one more thing: could you please @harry-cpp share with us any public URL when have anything working in MonoGame? We'd really like to see it in action :,-)

Thanks again!

**Comment by harry-cpp** [comment]
Why of course :) I already got the main rendering related parts working with WebGL 2 so the most problematic part right now is windowing / input.

Also thank you for your quick response!

**Comment by tebjan** [comment]
makes me wonder how hard it would be to implement a web platform target for Xenko/Stride, which is very similar to MonoGame:
https://github.com/stride3d/xenko
